More XFIRE-298 - I moved xmlunit/httpunit/junit into the parent pom because otherwise Maven was giving me NoClassDefFoundErrors.
git-svn-id: http://svn.codehaus.org/xfire/trunk/xfire@1318 c7d0bf07-ec0d-0410-b2cc-d48fa9be22ba